GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/6625c8068670dbbaff92cb6c

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"congthanh" ,
    "password":"truongcongT99",
    "name":"truong cong thanh"
}

###
PUT http://localhost:3001/api/users/6625c8068670dbbaff92cb6c
Content-Type: application/json

{
    "username":"congthanh" ,
    "password":"truongcongT",
    "name":"truong cong thanh"
}

###
DELETE http://localhost:3001/api/users/6625cf8b7acf3468333725dd