GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/6625e99af8ad756e7e00ee1b

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"congthanh1999" ,
    "password":"truongcongT99",
    "name":"truong cong thanh"
}

###
PUT http://localhost:3001/api/users/6625e99af8ad756e7e00ee1b
Content-Type: application/json

{
    "username":"congthanh" ,
    "password":"truongcongT99",
    "name":"truong cong thanh"
}

###
DELETE http://localhost:3001/api/users/6625e99af8ad756e7e00ee1b